#!/usr/bin/env python3
"""Generate the DBBASIC stage page object from the main app's sources.

Assembles puppet-stage/objects/puppet/stage.py from:
  ../../public/index.html   (stage DOM + CSS, script tags stripped)
  ../../public/stage.js     (verbatim frontend runtime)
  ./shim.js                 (DBBASIC transport adapter, loaded first)
  ../../characters/*/       (embedded as window.PUPPET_CHARACTERS)

Re-run after changing any of those so the package cannot drift from the app.
"""

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
OUT = HERE / "puppet-stage" / "objects" / "puppet" / "stage.py"

index_html = (ROOT / "public" / "index.html").read_text()
stage_js = (ROOT / "public" / "stage.js").read_text()
shim_js = (HERE / "shim.js").read_text()

css = re.search(r"<style>(.*?)</style>", index_html, re.S).group(1)
body = re.search(r"<body>(.*?)</body>", index_html, re.S).group(1)
body = re.sub(r"<script[^>]*>.*?</script>", "", body, flags=re.S).strip()

characters = {}
for manifest_path in sorted((ROOT / "characters").glob("*/manifest.json")):
    manifest = json.loads(manifest_path.read_text())
    svg = (manifest_path.parent / manifest["svg"]).read_text()
    characters[manifest_path.parent.name] = {"manifest": manifest, "svg": svg}

examples = {}
for script_path in sorted((ROOT / "examples").glob("*.txt")):
    examples[script_path.stem] = script_path.read_text()

html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Puppet Stage</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>{css}</style>
</head>
<body>
{body}
<script>window.PUPPET_CHARACTERS = {json.dumps(characters)};</script>
<script>window.PUPPET_EXAMPLES = {json.dumps(examples)};</script>
<script>
{shim_js}
</script>
<script>
{stage_js}
</script>
</body>
</html>
"""

assert "'''" not in html, "generated page would break the stage.py literal"

stage_py = f'''"""Puppet Stage page object. GENERATED by integrations/dbbasic/build.py — do not edit.

Serves the complete stage (HTML, CSS, runtime, characters) as one page.
Speech and direction go through the puppet_speak and puppet_cues objects.
"""

_HTML = r\'\'\'{html}\'\'\'


def GET(request):
    return {{"content_type": "text/html; charset=utf-8", "body": _HTML}}
'''

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(stage_py)
print(f"wrote {OUT} ({len(stage_py)//1024} KB, characters: {', '.join(characters)}, "
      f"examples: {', '.join(examples)})")
